### ISSUE TITLE
Please make this available on windows via winget

### ISSUE THREAD

**Issue by dheerajbhaskar** [chmln/sd#199] opened 2023-06-15 13:43 UTC
This is the output of `winget search sd`
I couldn't find `chmln` in the output, nor any relevant package manually either

```
Name                                   Id                                        Version                   Match   Source
--------------------------------------------------------------------------------------------------------------------------
EMS.GHS-SDS                            9PCFTG7HKXSN                              Unknown                           msstore
SD Price and Subscription              9P9W5PBLG3QR                              Unknown                           msstore
Dev Share                              9NBLGGH51S0C                              Unknown                           msstore
mySDS                                  9PC0D1DF2J0W                              Unknown                           msstore
Live Sun: SDO                          9N8R68SGJSML                              Unknown                           msstore
SDMS Offline Candidate Registration    9NGQT122VV1F                              Unknown                           msstore
ArcGIS Maps SDK for .NET Samples (WPF) 9MTP5013343H                              Unknown                           msstore
UAV Drone Controller App - SDD Test    9NBLGGH4T5G7                              Unknown                           msstore
APS SDK Test App                       9P7BZWGS4R5K                              Unknown                           msstore
Win32DiskImager                        Win32diskimager.win32diskimager           1.0.0                     Tag: sd winget
Raspberry Pi Imager                    RaspberryPiFoundation.RaspberryPiImager   1.7.5                     Tag: sd winget
balenaEtcher                           Balena.Etcher                             1.18.4                    Tag: sd winget
ScreenHunter                           WisdomSoftware.ScreenHunter               7.0.1449                          winget
MotionStudio                           WisdomSoftware.MotionStudio               4.1                               winget
MotionGIF                              WisdomSoftware.MotionGIF                  4.1                               winget
Free Media Player                      WisdomSoftware.FreeMediaPlayer            1.0.109                           winget
AutoScreenRecorder                     WisdomSoftware.AutoScreenRecorder         5.0.781                           winget
Widelands                              WidelandsDevelopmentTeam.Widelands        1.0                               winget
VSDC Free Screen Recorder              VSDC.ScreenRecorder                       1.3.3.0                           winget
VSDC Free Video Editor                 VSDC.Editor                               8.1.3.459                         winget
LibreOffice SDK                        TheDocumentFoundation.LibreOffice.SDK     7.4.3.2                           winget
消极压制                               TedZyzsdy.NegativeEncoder                 5.0.7                             winget
Cosmos DB Explorer                     SachaBruttin.CosmosDBExplorer             0.9.8-beta                        winget
R&S® IETDView Publish                  Rohde&Schwarz.SDC.IETDViewPublish         6.3                               winget
R&S® IETDView Autark Bw                Rohde&Schwarz.SDC.IETDViewAutarkBw        6.3                               winget
R&S® IETDView Autark                   Rohde&Schwarz.SDC.IETDViewAutark          6.3                               winget
Lively Wallpaper                       rocksdanister.LivelyWallpaper             2.0.6.5                           winget
Another Redis Desktop Manager          qishibo.AnotherRedisDesktopManager        1.5.9                             winget
Persepolis Download Manager            PersepolisDownloadManager.Persepolis      3.2.0.0                           winget
Playdate SDK                           Panic.PlaydateSDK                         2.0.0-beta.4                      winget
BatteryBar                             OsirisDevelopment.BatteryBar              3.6.6                             winget
AVS Disc Creator                       OnlineMediaTechnologiesLtd.AVSDiscCreator 6.2.4.564                         winget
Octopus Deploy Tentacle                OctopusDeploy.Tentacle                    6.3.417                           winget
Octopus Deploy Server                  OctopusDeploy.Server                      2023.1.9791                       winget
NVIDIA Video Effects                   Nvidia.VideoEffectsSDK.20xx-Turing        0.6.5                             winget
NirSoft WhoisThisDomain                NirSoft.WhoisThisDomain                   2.46                              winget
Rawrite32                              netbsd.rawrite32                          1.0.9.0                           winget
Microsoft Teams Continuous Deployment  Microsoft.Teams.ContinuousDeployment      1.5.00.31365                      winget
Microsoft MPI SDK                      Microsoft.msmpisdk                        10.1.12498.18                     winget
Microsoft .NET SDK 8.0 Preview         Microsoft.DotNet.SDK.Preview              8.0.100-preview.5.23303.2         winget
Microsoft .NET SDK 7.0                 Microsoft.DotNet.SDK.7                    7.0.304                           winget
Microsoft .NET SDK 6.0                 Microsoft.DotNet.SDK.6                    6.0.410                           winget
Microsoft .NET SDK 5.0                 Microsoft.DotNet.SDK.5                    5.0.408                           winget
Microsoft .NET SDK 3.1                 Microsoft.DotNet.SDK.3_1                  3.1.426                           winget
NTFS Data Recovery                     LSoftTechnologies.NTFSDataRecovery        22                                winget
Vulkan SDK                             KhronosGroup.VulkanSDK                    1.3.231.1                         winget
Aventuras de quintal                   IsaqueS.AventurasDeQuintal                1.0.0                             winget
Google Cloud SDK                       Google.CloudSDK                           431.0.0                           winget
DisplayLink Graphics                   DisplayLink.GraphicsDriver                11.0.2412.0                       winget
CubicSDR                               CubicSDR.CubicSDR                         0.2.5                             winget
C-Dogs SDL                             CongusBongus.CDogsSDL                     1.4.2                             winget
Cocos Dashboard                        Cocos.CocosDashboard                      1.3.2.0321                        winget
Bethesda.net Launcher                  Bethesda.Launcher                         1.84.0                            winget
Jerry - Das Schachprogramm             asdfjkl.JerryChess                        4.2.1                             winget
Avantis Director                       Allen&Heath.AvantisDirector               V1.11 - Rev. 64180                winget
lsdeer                                 AlexanderPershin.lsdeer                   0.1.6                             winget
actionlint                             rhysd.actionlint                          1.6.24                            winget
即时设计                               DiegoFernandes.jsdesign                   1.0.7                             winget
Instaminutes Desktop App               Instaminutes.InstaminutesDesktopApp       0.1.0                             winget
AllDup                                 MTSD.AllDup                               4.5.46                            winget
Kingston SSD Manager x64               Kingston.SSDManager                       1.5.2.6                           winget
Doomsday Last Survivors                IGGInc.Doomsday                           1.0.21                            winget
SDRangel                               f4exb.sdrangel                            7.14.2                            winget
FMS Data Manager                       Navigraph.FMSDataManager                  8.11.1505                         winget
Windows SDK                            Microsoft.WindowsSDK.10.0.17763           10.0.17736.0                      winget
Windows Software Development Kit       Microsoft.WindowsSDK.10.0.19041           10.0.19041.685                    winget
Windows SDK                            Microsoft.WindowsSDK.10.0.18362           10.0.18362.0                      winget
Windows Software Development Kit       Microsoft.WindowsSDK.10.0.22000           10.0.22000.832                    winget
Windows Software Development Kit       Microsoft.WindowsSDK.10.0.22621           10.0.22621.2                      winget
Doomsday Engine                        DoomsdayEngine.DoomsdayEngine             2.3.1.3685                        winget
SDL Trados Studio 2021 SR2             Trados.TradosStudio.2021                  16.2.9305                         winget
MonoGame SDK                           MonoGame.MonoGame                         3.7.1.189                         winget
Microsoft .NET Core SDK Uninstall Tool Microsoft.dotnetUninstallTool             4.80.595                          winget
libjpeg-turbo SDK for Visual C++       libjpeg-turbo.libjpeg-turbo.VC            2.1.5.1                           winget
libjpeg-turbo SDK for GCC              libjpeg-turbo.libjpeg-turbo.GCC           2.1.5.1                           winget
Windows App SDK                        Microsoft.WindowsAppRuntime.1.0           1.0.4                             winget
Windows App SDK                        Microsoft.WindowsAppRuntime.1.1           1.1.5                             winget
Windows App SDK                        Microsoft.WindowsAppRuntime.1.2           1.2.2                             winget
Texnomic SecureDNS Terminal            Texnomic.SecureDNS-Terminal               0.3                       Monike… winget
Microsoft Web Deploy                   Microsoft.WebDeploy                       10.0.1973                 Monike… winget
Tesseract-OCR - open source OCR engine UB-Mannheim.TesseractOCR                  5.3.1.20230401            Comman… winget
Linrad                                 SM5BSZ.Linrad                             05.01                     Tag: s… winget
NVIDIA CUDA Toolkit                    Nvidia.CUDA                               12.1                      Tag: s… winget
Mono for Windows                       Mono.Mono                                 6.12.0.182                Tag: s… winget
MiniTool Partition Wizard Free         MiniTool.PartitionWizard.Free             12.7                      Tag: s… winget
MSIX Core                              Microsoft.MSIXCore                        1.1.0.0                   Tag: s… winget
VeraCrypt                              IDRIX.VeraCrypt                           1.25.9                    Tag: s… winget
CrystalDiskMark Shizuku Edition        CrystalDewWorld.CrystalDiskMark.ShizukuE… 8.0.4                     Tag: s… winget
CrystalDiskMark                        CrystalDewWorld.CrystalDiskMark           8.0.4                     Tag: s… winget
CrystalDiskInfo Shizuku Edition        CrystalDewWorld.CrystalDiskInfo.ShizukuE… 9.0.1                     Tag: s… winget
CrystalDiskInfo Kurei Kei Edition      CrystalDewWorld.CrystalDiskInfo.KureiKei… 9.0.1                     Tag: s… winget
CrystalDiskInfo                        CrystalDewWorld.CrystalDiskInfo           9.0.1                     Tag: s… winget
ChefDK                                 ChefSoftware.ChefDK                       4.13.3.1                  Tag: s… winget
Batch Image Converter Free Edition     BinaryMark.BatchImageConverter            5.6                       Tag: P… winget
Avocode                                Avocode.Avocode                           4.15.6                    Tag: p… winget
Argus Monitor                          Argotronic.ArgusMonitor                   6.2.03                    Tag: s… winget
支付宝开放平台密钥工具                 Alibaba.AlipayKeyTool                     2.0.3                     Tag: s… winget
Another Qt installer                   miurahr.aqtinstall                        3.1.6                     Tag: a… winget
zoxide                                 ajeetdsouza.zoxide                        0.9.1                     Tag: f… winget
HDCleaner                              KurtZimmermann.HDCleaner                  2.051                     Tag: s… winget
Azure Cosmos DB Emulator               Microsoft.Azure.CosmosEmulator            2.14.12                   Tag: C… winget
SolidigmTM Storage Tool                Solidigm.StorageTool                      1.8                       Tag: s… winget

```

**Comment by CosmicHorrorDev** [comment] 2023-06-15 14:55
I'm planning on adding windows build artifacts to the next release, but I don't know any of the other work that goes into making something available from `winget`

I'm going to close this as a duplicate of #90

**Closed by CosmicHorrorDev** 2023-06-15 14:55 UTC
