### ISSUE TITLE
How to disable global mode

### ISSUE THREAD

**Issue by azzamsa** [chmln/sd#131] opened 2021-06-14 09:49 UTC
Hi.

Given the text below:

```toml
[package]
name = "foo"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { version = "0.5.0-rc.1", default-features = false }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_qs = "0.8.3"
reqwest = { version = "0.11.3", features = ["json"] }
thiserror = "1.0.25"
```

I can match only the first match by emitting `/g` on my regex:

![image](https://user-images.githubusercontent.com/17734314/121873024-22266d00-cd30-11eb-9bd3-3ba0e8753eb3.png)

However, I can't do this in sd. I don't find a `single line flag`:

```
OPTIONS:
    -f, --flags <flags>
            Regex flags. May be combined (like `-f mc`).

            c - case-sensitive
            e - disable multi-line matching
            i - case-insensitive
            m - multi-line matching
            s - make `.` match newlines
            w - match full words only
```

It will change all the matches in the text, not once.

```
❯ sd -p -f e '[0-9]+.[0-9]+.[0-9]+' '1.0.3' Cargo.toml

[package]
name = "foo"
version = "1.0.3"
edition = "2018"

[dependencies]
rocket = { version = "1.0.3-rc.1", default-features = false }
serde = { version = "1.0.3", features = ["derive"] }
serde_json = "1.0.3"
serde_qs = "1.0.3 
```

```
❯ sd --help
sd 0.7.6
```

Any suggestion?
Thanks in advance.

**Comment by balupton** [comment] 2021-12-02 06:24
dupe of https://github.com/chmln/sd/issues/105

**Comment by CosmicHorrorDev** [comment] 2023-12-08 00:45
This should be resolved now that you can use the `-n` aka `--max-replacements` flag to limit the number of desired replacements

**Closed by CosmicHorrorDev** 2023-12-08 00:45 UTC
Labels: C-question

**Comment by bAndie91** [comment] 2024-12-10 14:50
> This should be resolved now that you can use the `-n` aka `--max-replacements` flag to limit the number of desired replacements

`-n 1` replaces at most 1 match in the whole input, not per-line. even with `-f e` (https://github.com/chmln/sd) flag.

version: `eb51bdf ➼ v1.0.0`
