### ISSUE TITLE
Can you remove a line with sd?

### ISSUE THREAD

**Issue by EmilSodergren** [chmln/sd#132] opened 2021-06-29 20:01 UTC
Is it possible to remove lines with sd? You could of course "replace line with empty" but that leaves unwanted empty blank lines. With sed you write `sed -i '/pattern to match/d' ./infile`. Is there something similar in sd? I think that functionality is the only thing that still keeps sed in my toolbox... :smile:

**Comment by murlakatamenka** [comment] 2021-06-30 02:48
What about

```sh
sd '\n+' '' FILE
```
?

**Comment by jorunfa** [comment] 2021-06-30 11:45
Just use '\n' in your pattern?

```
sd 'foo\n' ''
```

**Comment by balupton** [comment] 2021-12-02 06:30
possible dupe of https://github.com/chmln/sd/issues/99

**Comment by CosmicHorrorDev** [comment] 2023-10-22 00:55
As @jorunfa mentioned you just need to include the newline in the pattern. If you want to support text that uses `\r\n` as well then you can use `\r?\n`

**Closed by CosmicHorrorDev** 2023-10-22 00:55 UTC
Labels: M-needs triage
